local ns = select(2, ...)

ns:RegisterLocale("deDE", {
    TAB_TOOLTIP = "BoE — Gebietsbeute",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Beim Anlegen gebundene Ausrüstung aus den Freiluftgebieten der gewählten Erweiterung.",
    WORLD_DROPS = "Weltbeute",
    OUTDOOR_NO_DATA = "Für diese Erweiterung wurde keine BoE-Freiluftausrüstung gefunden.",
    OUTDOOR_LOADING = "Freiluftbeute wird geladen…",
    INSTANCE_LOADING = "Instanzbeute wird geladen…",
    OUTDOOR_FILTER_NO_DATA = "Für diesen Filter wurde keine BoE-Freiluftausrüstung gefunden.",
    MORE_SOURCES = "+%d weitere",
    OUTDOOR_REFRESHED = "Freiluftbeute wurde aktualisiert.",
    REFRESH_TOOLTIP = "Leert den Boeloot-Zwischenspeicher und lädt die Beute der ausgewählten Instanz neu.",
    NO_INSTANCE = "Wählt einen Schlachtzug oder Dungeon im Abenteuerführer aus.",
    NO_DATA = "Für diese Instanz und diesen Schwierigkeitsgrad wurden keine ausrüstbaren Gegenstände unter Gebietsbeute gefunden.",
    ATT_MISSING = "AllTheThings ist nicht installiert oder deaktiviert.",
    ATT_LOADING = "Die Beutedatenbank wird noch geladen…",
    ATT_INCOMPATIBLE = "Die installierte AllTheThings-API ist nicht mit Boeloot kompatibel.",
    ATT_INSTANCE_MISSING = "Für diese Instanz sind keine Beutedaten verfügbar.",
    TRASH = "Trash",
    UNKNOWN = "Unbekannt",
    ITEM_FALLBACK = "Gegenstand %d",
    REFRESHED = "Die Beutedaten der ausgewählten Instanz wurden aktualisiert.",
    CACHE_CLEARED = "Laufzeit-Zwischenspeicher geleert.",
    COMMAND_HELP = "Befehle: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Blizzard_EncounterJournal konnte nicht geladen werden: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Gegenstands-ID kopieren",
    COPY_ITEM_ID_PROMPT = "Drücke Strg+C, um die Gegenstands-ID zu kopieren.",
})
