local ns = select(2, ...)

ns:RegisterLocale("enGB", {
    TAB_TOOLTIP = "BoE — Zone Drops",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Bind-on-equip gear from the outdoor zones of the selected expansion.",
    WORLD_DROPS = "World Drops",
    OUTDOOR_NO_DATA = "No outdoor BoE gear was found for this expansion.",
    OUTDOOR_LOADING = "Loading outdoor loot…",
    INSTANCE_LOADING = "Loading instance loot…",
    OUTDOOR_FILTER_NO_DATA = "No outdoor BoE gear matches this filter.",
    MORE_SOURCES = "+%d more",
    OUTDOOR_REFRESHED = "Outdoor loot data refreshed.",
    REFRESH_TOOLTIP = "Clear the Boeloot cache and reload the selected instance's loot.",
    NO_INSTANCE = "Select a raid or dungeon in the Adventure Guide.",
    NO_DATA = "No equippable items were found in Zone Drops for this instance and difficulty.",
    ATT_MISSING = "AllTheThings is not installed or is disabled.",
    ATT_LOADING = "The loot database is still loading…",
    ATT_INCOMPATIBLE = "The installed AllTheThings API is incompatible with Boeloot.",
    ATT_INSTANCE_MISSING = "No loot data is available for this instance.",
    TRASH = "Trash",
    UNKNOWN = "Unknown",
    ITEM_FALLBACK = "Item %d",
    REFRESHED = "Loot data refreshed for the selected instance.",
    CACHE_CLEARED = "Runtime cache cleared.",
    COMMAND_HELP = "Commands: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Unable to load Blizzard_EncounterJournal: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Copy item ID",
    COPY_ITEM_ID_PROMPT = "Press Ctrl+C to copy the item ID.",
})
