local ns = select(2, ...)

ns:RegisterLocale("esMX", {
    TAB_TOOLTIP = "BoE — Botín de zona",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Equipo ligado al equiparlo de las zonas exteriores de la expansión seleccionada.",
    WORLD_DROPS = "Botín del mundo",
    OUTDOOR_NO_DATA = "No se encontró equipo BoE exterior para esta expansión.",
    OUTDOOR_LOADING = "Cargando el botín exterior…",
    INSTANCE_LOADING = "Cargando el botín de la estancia…",
    OUTDOOR_FILTER_NO_DATA = "Ningún equipo BoE exterior coincide con este filtro.",
    MORE_SOURCES = "+%d más",
    OUTDOOR_REFRESHED = "Botín exterior actualizado.",
    REFRESH_TOOLTIP = "Vacía la caché de Boeloot y vuelve a cargar el botín de la instancia seleccionada.",
    NO_INSTANCE = "Selecciona una banda o calabozo en la guía de aventuras.",
    NO_DATA = "No se encontraron objetos equipables en Botín de zona para esta instancia y dificultad.",
    ATT_MISSING = "AllTheThings no está instalado o está desactivado.",
    ATT_LOADING = "La base de datos de botín todavía se está cargando…",
    ATT_INCOMPATIBLE = "La API de AllTheThings instalada no es compatible con Boeloot.",
    ATT_INSTANCE_MISSING = "No hay datos de botín disponibles para esta instancia.",
    TRASH = "Enemigos comunes",
    UNKNOWN = "Desconocido",
    ITEM_FALLBACK = "Objeto %d",
    REFRESHED = "Se actualizaron los datos de botín de la instancia seleccionada.",
    CACHE_CLEARED = "Caché temporal vaciada.",
    COMMAND_HELP = "Comandos: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "No se pudo cargar Blizzard_EncounterJournal: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Copiar ID de objeto",
    COPY_ITEM_ID_PROMPT = "Presiona Ctrl+C para copiar el ID del objeto.",
})
