local ns = select(2, ...)

ns:RegisterLocale("frFR", {
    TAB_TOOLTIP = "BoE — Butin de zone",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Équipement lié quand équipé provenant des zones extérieures de l’extension sélectionnée.",
    WORLD_DROPS = "Butin mondial",
    OUTDOOR_NO_DATA = "Aucun équipement BoE extérieur n’a été trouvé pour cette extension.",
    OUTDOOR_LOADING = "Chargement du butin extérieur…",
    INSTANCE_LOADING = "Chargement du butin de l’instance…",
    OUTDOOR_FILTER_NO_DATA = "Aucun équipement BoE extérieur ne correspond à ce filtre.",
    MORE_SOURCES = "+%d autres",
    OUTDOOR_REFRESHED = "Butin extérieur actualisé.",
    REFRESH_TOOLTIP = "Vide le cache de Boeloot et recharge le butin de l’instance sélectionnée.",
    NO_INSTANCE = "Sélectionnez un raid ou un donjon dans le guide de l’aventurier.",
    NO_DATA = "Aucun objet équipable n’a été trouvé dans le Butin de zone pour cette instance et cette difficulté.",
    ATT_MISSING = "AllTheThings n’est pas installé ou est désactivé.",
    ATT_LOADING = "La base de données de butin est encore en cours de chargement…",
    ATT_INCOMPATIBLE = "L’API AllTheThings installée n’est pas compatible avec Boeloot.",
    ATT_INSTANCE_MISSING = "Aucune donnée de butin n’est disponible pour cette instance.",
    TRASH = "Ennemis communs",
    UNKNOWN = "Inconnu",
    ITEM_FALLBACK = "Objet %d",
    REFRESHED = "Les données de butin de l’instance sélectionnée ont été actualisées.",
    CACHE_CLEARED = "Cache temporaire vidé.",
    COMMAND_HELP = "Commandes : /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Impossible de charger Blizzard_EncounterJournal : %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Copier l’ID de l’objet",
    COPY_ITEM_ID_PROMPT = "Appuyez sur Ctrl+C pour copier l’ID de l’objet.",
})
