local ns = select(2, ...)

ns:RegisterLocale("itIT", {
    TAB_TOOLTIP = "BoE — Bottino di zona",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Equipaggiamento vincolato all’uso dalle zone esterne dell’espansione selezionata.",
    WORLD_DROPS = "Bottino mondiale",
    OUTDOOR_NO_DATA = "Non è stato trovato equipaggiamento BoE esterno per questa espansione.",
    OUTDOOR_LOADING = "Caricamento del bottino esterno…",
    INSTANCE_LOADING = "Caricamento del bottino dell'istanza…",
    OUTDOOR_FILTER_NO_DATA = "Nessun equipaggiamento BoE esterno corrisponde a questo filtro.",
    MORE_SOURCES = "+%d altre",
    OUTDOOR_REFRESHED = "Bottino esterno aggiornato.",
    REFRESH_TOOLTIP = "Svuota la cache di Boeloot e ricarica il bottino dell’istanza selezionata.",
    NO_INSTANCE = "Seleziona un’incursione o una spedizione nella Guida alle Avventure.",
    NO_DATA = "Non sono stati trovati oggetti equipaggiabili nel Bottino di zona per questa istanza e difficoltà.",
    ATT_MISSING = "AllTheThings non è installato o è disattivato.",
    ATT_LOADING = "Il database del bottino è ancora in fase di caricamento…",
    ATT_INCOMPATIBLE = "L’API di AllTheThings installata non è compatibile con Boeloot.",
    ATT_INSTANCE_MISSING = "Non sono disponibili dati sul bottino per questa istanza.",
    TRASH = "Nemici comuni",
    UNKNOWN = "Sconosciuto",
    ITEM_FALLBACK = "Oggetto %d",
    REFRESHED = "I dati sul bottino dell’istanza selezionata sono stati aggiornati.",
    CACHE_CLEARED = "Cache temporanea svuotata.",
    COMMAND_HELP = "Comandi: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Impossibile caricare Blizzard_EncounterJournal: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Copia ID oggetto",
    COPY_ITEM_ID_PROMPT = "Premi Ctrl+C per copiare l’ID dell’oggetto.",
})
