local ns = select(2, ...)

ns:RegisterLocale("koKR", {
    TAB_TOOLTIP = "BoE — 지역 전리품",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "선택한 확장팩 야외 지역의 착용 시 귀속 장비입니다.",
    WORLD_DROPS = "월드 드롭",
    OUTDOOR_NO_DATA = "이 확장팩의 야외 BoE 장비를 찾을 수 없습니다.",
    OUTDOOR_LOADING = "야외 전리품 불러오는 중…",
    INSTANCE_LOADING = "인스턴스 전리품 불러오는 중…",
    OUTDOOR_FILTER_NO_DATA = "이 필터에 맞는 야외 BoE 장비가 없습니다.",
    MORE_SOURCES = "외 %d개",
    OUTDOOR_REFRESHED = "야외 전리품 데이터를 새로 고쳤습니다.",
    REFRESH_TOOLTIP = "Boeloot 캐시를 비우고 선택한 인스턴스의 전리품을 다시 불러옵니다.",
    NO_INSTANCE = "모험 안내서에서 공격대 또는 던전을 선택하세요.",
    NO_DATA = "이 인스턴스와 난이도의 지역 전리품에서 착용 가능한 아이템을 찾을 수 없습니다.",
    ATT_MISSING = "AllTheThings가 설치되지 않았거나 비활성화되어 있습니다.",
    ATT_LOADING = "전리품 데이터베이스를 아직 불러오는 중입니다…",
    ATT_INCOMPATIBLE = "설치된 AllTheThings API가 Boeloot와 호환되지 않습니다.",
    ATT_INSTANCE_MISSING = "이 인스턴스의 전리품 데이터가 없습니다.",
    TRASH = "일반 몬스터",
    UNKNOWN = "알 수 없음",
    ITEM_FALLBACK = "아이템 %d",
    REFRESHED = "선택한 인스턴스의 전리품 데이터를 새로 고쳤습니다.",
    CACHE_CLEARED = "임시 캐시를 비웠습니다.",
    COMMAND_HELP = "명령어: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Blizzard_EncounterJournal을 불러올 수 없습니다: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "아이템 ID 복사",
    COPY_ITEM_ID_PROMPT = "Ctrl+C를 눌러 아이템 ID를 복사하세요.",
})
