local ns = select(2, ...)

ns:RegisterLocale("ptBR", {
    TAB_TOOLTIP = "BoE — Saque da área",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Equipamento vinculado ao equipar das áreas externas da expansão selecionada.",
    WORLD_DROPS = "Saque do mundo",
    OUTDOOR_NO_DATA = "Nenhum equipamento BoE externo foi encontrado para esta expansão.",
    OUTDOOR_LOADING = "Carregando o saque externo…",
    INSTANCE_LOADING = "Carregando o saque da instância…",
    OUTDOOR_FILTER_NO_DATA = "Nenhum equipamento BoE externo corresponde a este filtro.",
    MORE_SOURCES = "+%d outras",
    OUTDOOR_REFRESHED = "Saque externo atualizado.",
    REFRESH_TOOLTIP = "Limpa o cache do Boeloot e recarrega o saque da instância selecionada.",
    NO_INSTANCE = "Selecione uma raide ou masmorra no Guia de Aventuras.",
    NO_DATA = "Nenhum item equipável foi encontrado no Saque da área para esta instância e dificuldade.",
    ATT_MISSING = "O AllTheThings não está instalado ou está desativado.",
    ATT_LOADING = "O banco de dados de saque ainda está sendo carregado…",
    ATT_INCOMPATIBLE = "A API instalada do AllTheThings é incompatível com o Boeloot.",
    ATT_INSTANCE_MISSING = "Não há dados de saque disponíveis para esta instância.",
    TRASH = "Inimigos comuns",
    UNKNOWN = "Desconhecido",
    ITEM_FALLBACK = "Item %d",
    REFRESHED = "Os dados de saque da instância selecionada foram atualizados.",
    CACHE_CLEARED = "Cache temporário limpo.",
    COMMAND_HELP = "Comandos: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Não foi possível carregar Blizzard_EncounterJournal: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Copiar ID do item",
    COPY_ITEM_ID_PROMPT = "Pressione Ctrl+C para copiar o ID do item.",
})
