local ns = select(2, ...)

ns:RegisterLocale("ruRU", {
    TAB_TOOLTIP = "BoE — добыча локации",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "Становящаяся персональной при надевании экипировка из зон открытого мира выбранного дополнения.",
    WORLD_DROPS = "Общий мировой лут",
    OUTDOOR_NO_DATA = "Для этого дополнения не найдено BoE-экипировки открытого мира.",
    OUTDOOR_LOADING = "Загрузка добычи открытого мира…",
    INSTANCE_LOADING = "Загрузка добычи инстанса…",
    OUTDOOR_FILTER_NO_DATA = "Для этого фильтра не найдено BoE-экипировки открытого мира.",
    MORE_SOURCES = "ещё: %d",
    OUTDOOR_REFRESHED = "Данные добычи открытого мира обновлены.",
    REFRESH_TOOLTIP = "Очистить кеш Boeloot и заново загрузить добычу выбранного подземелья или рейда.",
    NO_INSTANCE = "Выберите рейд или подземелье в Путеводителе по приключениям.",
    NO_DATA = "В добыче локации нет экипируемых предметов для выбранного инстанса и сложности.",
    ATT_MISSING = "AllTheThings не установлен или отключён.",
    ATT_LOADING = "База данных добычи всё ещё загружается…",
    ATT_INCOMPATIBLE = "API установленной версии AllTheThings несовместим с Boeloot.",
    ATT_INSTANCE_MISSING = "Для этого инстанса нет данных о добыче.",
    TRASH = "Обычные противники",
    UNKNOWN = "Неизвестно",
    ITEM_FALLBACK = "Предмет %d",
    REFRESHED = "Данные добычи выбранного инстанса обновлены.",
    CACHE_CLEARED = "Временный кеш очищен.",
    COMMAND_HELP = "Команды: /boeloot, refresh, clear, status",
    JOURNAL_LOAD_FAILED = "Не удалось загрузить Blizzard_EncounterJournal: %s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "Скопировать ID предмета",
    COPY_ITEM_ID_PROMPT = "Нажмите Ctrl+C, чтобы скопировать ID предмета.",
})
