local ns = select(2, ...)

ns:RegisterLocale("zhCN", {
    TAB_TOOLTIP = "BoE — 区域掉落",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "所选资料片户外区域的装备后绑定装备。",
    WORLD_DROPS = "世界掉落",
    OUTDOOR_NO_DATA = "未找到此资料片的户外BoE装备。",
    OUTDOOR_LOADING = "正在加载户外掉落…",
    INSTANCE_LOADING = "正在加载副本掉落…",
    OUTDOOR_FILTER_NO_DATA = "没有符合此筛选条件的户外BoE装备。",
    MORE_SOURCES = "另有%d个",
    OUTDOOR_REFRESHED = "已刷新户外掉落数据。",
    REFRESH_TOOLTIP = "清除Boeloot缓存，并重新加载所选副本的掉落。",
    NO_INSTANCE = "请在冒险指南中选择一个团队副本或地下城。",
    NO_DATA = "此副本和难度的区域掉落中未找到可装备物品。",
    ATT_MISSING = "AllTheThings未安装或已禁用。",
    ATT_LOADING = "掉落数据库仍在加载…",
    ATT_INCOMPATIBLE = "已安装的AllTheThings API与Boeloot不兼容。",
    ATT_INSTANCE_MISSING = "没有此副本的掉落数据。",
    TRASH = "小怪",
    UNKNOWN = "未知",
    ITEM_FALLBACK = "物品 %d",
    REFRESHED = "已刷新所选副本的掉落数据。",
    CACHE_CLEARED = "运行时缓存已清除。",
    COMMAND_HELP = "命令：/boeloot、refresh、clear、status",
    JOURNAL_LOAD_FAILED = "无法加载Blizzard_EncounterJournal：%s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "复制物品 ID",
    COPY_ITEM_ID_PROMPT = "按 Ctrl+C 复制物品 ID。",
})
