local ns = select(2, ...)

ns:RegisterLocale("zhTW", {
    TAB_TOOLTIP = "BoE — 區域掉落",
    OUTDOOR_TITLE = "BoE Loot",
    OUTDOOR_CARD_DESCRIPTION = "所選資料片戶外區域的裝備後綁定裝備。",
    WORLD_DROPS = "世界掉落",
    OUTDOOR_NO_DATA = "未找到此資料片的戶外BoE裝備。",
    OUTDOOR_LOADING = "正在載入戶外掉落…",
    INSTANCE_LOADING = "正在載入副本掉落…",
    OUTDOOR_FILTER_NO_DATA = "沒有符合此篩選條件的戶外BoE裝備。",
    MORE_SOURCES = "另有%d個",
    OUTDOOR_REFRESHED = "已重新整理戶外掉落資料。",
    REFRESH_TOOLTIP = "清除Boeloot快取，並重新載入所選副本的掉落。",
    NO_INSTANCE = "請在冒險指南中選擇一個團隊副本或地城。",
    NO_DATA = "此副本和難度的區域掉落中未找到可裝備物品。",
    ATT_MISSING = "AllTheThings未安裝或已停用。",
    ATT_LOADING = "掉落資料庫仍在載入…",
    ATT_INCOMPATIBLE = "已安裝的AllTheThings API與Boeloot不相容。",
    ATT_INSTANCE_MISSING = "沒有此副本的掉落資料。",
    TRASH = "小怪",
    UNKNOWN = "未知",
    ITEM_FALLBACK = "物品 %d",
    REFRESHED = "已重新整理所選副本的掉落資料。",
    CACHE_CLEARED = "執行階段快取已清除。",
    COMMAND_HELP = "指令：/boeloot、refresh、clear、status",
    JOURNAL_LOAD_FAILED = "無法載入Blizzard_EncounterJournal：%s",
    ITEM_ID_BUTTON = "ID",
    COPY_ITEM_ID_TOOLTIP = "複製物品 ID",
    COPY_ITEM_ID_PROMPT = "按 Ctrl+C 複製物品 ID。",
})
